// Questions de quiz par cours : [question, BONNE réponse, faux 1, faux 2, faux 3] (l'ordre est mélangé à l'affichage).
export const QUESTIONS = {
1: [
["Où se place le verbe en japonais ?","À la fin de la phrase","Au début","Au milieu","Juste après le sujet"],
["Comment dit-on « des chats » ?","Neko (pas de pluriel)","Nekos","Nekoes","Les neko"],
["Comment se prononce は quand c'est une particule ?","wa","ha","ba","fa"],
["Que fait la particule は ?","Elle marque le thème de la phrase","Elle marque le verbe","Elle indique le pluriel","Elle pose une question"],
["Que devient le verbe selon le sujet (je, tu, nous…) ?","Il ne change pas","Il prend une terminaison différente","Il passe au pluriel","Il se place au début"],
["Que se passe-t-il souvent avec « watashi wa » (je) ?","On l'omet quand c'est évident","Il est toujours obligatoire","Il se place à la fin","Il remplace le verbe"],
["Comment dit-on « Je suis français(e) » ?","Furansujin desu","Furansu ga desu","Furansujin ka","Furansu ni desu"],
["Quel suffixe s'ajoute au nom du pays pour la nationalité ?","じん (jin)","さん (san)","です (desu)","ます (masu)"],
["Que signifie « Nihonjin » ?","Japonais(e)","Chinois(e)","Américain(e)","Belge"],
["Que signifie « Igirisujin » ?","Anglais(e)","Suisse","Belge","Américain(e)"],
["Que signifie « Suisujin » ?","Suisse","Belge","Français(e)","Anglais(e)"],
["Quelle forme est la plus formelle pour dire son nom ?","〜ともうします (to moshimasu)","〜といいます (to iimasu)","〜です (desu)","〜は (wa)"],
["« Hajimemashite » se dit…","En rencontrant quelqu'un","En quittant quelqu'un","Pour remercier","Pour s'excuser"],
["Que signifie « Yoroshiku onegaishimasu » ?","Ravi(e) de faire votre connaissance","Excusez-moi","Au revoir","Je mange"],
["« Konnichiwa » se dit…","Dans la journée","Le matin","Le soir","Pour dire au revoir"],
["Que signifie « Ohayou » ?","Bonjour (matin)","Bonsoir","Au revoir","Merci"],
["Que signifie « Konbanwa » ?","Bonsoir","Bonjour (matin)","Merci","S'il vous plaît"],
["Que signifie « Sumimasen » ?","Excusez-moi","Merci","Oui","Non"],
["Que signifie « Arigatou » ?","Merci","Oui","Non","Au revoir"],
["Que signifie « Sayounara » ?","Au revoir","Bonjour","Bonsoir","Merci"],
["Que signifie « Shumi » ?","Hobby","École","Eau","Train"],
["Que signifie « Ongaku » ?","Musique","Cuisine","Voyage","Sport"],
["Que signifie « Ryouri » ?","Cuisine","Musique","Voyage","Manga"],
["Que signifie « Tabi » ?","Voyage","Sport","Cuisine","Musique"],
["Combien de caractères compte l'hiragana de base ?","46","26","80","100"],
["À quoi servent surtout les katakana ?","Mots étrangers et noms propres non japonais","Terminaisons verbales","Particules grammaticales","Nombres"],
["Combien de kanji faut-il environ pour le niveau N5 ?","Environ 80","Environ 10","Environ 500","Environ 2000"],
["Quel est l'ordre d'apprentissage conseillé ?","Hiraganas, katakanas, puis kanjis","Kanjis, hiraganas, puis katakanas","Katakanas, kanjis, puis hiraganas","Kanjis, katakanas, puis hiraganas"],
["Que signifie « Luffy wa kaizoku desu » ?","Luffy est un pirate","Luffy mange","Luffy est français","Luffy dort"],
["Que signifie « Neko wa kawaii desu » ?","Le chat est mignon","Le chien est mignon","Le chat est grand","Le chat mange"],
["Que signifie « Sensei » ?","Professeur","Ami(e)","École","Étudiant"],
["Que signifie « Tomodachi » ?","Ami(e)","Professeur","Moi","Toi"],
["Comment dit-on « Mon hobby est la musique » ?","Shumi wa ongaku desu","Ongaku wa shumi ka","Shumi ga ongaku ni","Ongaku desu wa shumi"]
],
2: [
["Quel mot en fin de phrase transforme une phrase en question ?","ka","wa","ga","no"],
["Comment nier l'adjectif en i « takai » ?","Takakunai","Takai nai","Takanai","Takaku desu"],
["Comment nier l'adjectif en na « genki » ?","Genki janai","Genki kunai","Genki nai","Genki ka"],
["Pour nier un adjectif en i, on remplace い par…","くない (kunai)","じゃない (janai)","ない (nai)","ます (masu)"],
["Pour nier un adjectif en na, on ajoute…","じゃない (janai)","くない (kunai)","ます (masu)","か (ka)"],
["Quelle est la forme polie de « janai » ?","jaa arimasen","jaa imasu","kunai arimasen","ka arimasen"],
["« Kirei » finit par « i » mais c'est un adjectif en…","na","i","verbe","particule"],
["« Benri » (pratique) est un adjectif en…","na","i","verbe","particule"],
["« Oishii » (délicieux) est un adjectif en…","i","na","verbe","particule"],
["Que signifie « Samui » ?","Froid","Chaud","Fort","Faible"],
["Que signifie « Atsui » ?","Chaud","Froid","Calme","Pratique"],
["Que signifie « Muzukashii » ?","Compliqué","Facile","Délicieux","Pratique"],
["Que signifie « Kantan » ?","Facile / simple","Compliqué","Calme","Fort"],
["Que signifie « Shizuka » ?","Calme","Incroyable","Chaud","Délicieux"],
["Que signifie « Yowai » ?","Faible","Fort","Bon","Froid"],
["Que signifie « Tsuyoi » ?","Fort","Faible","Froid","Calme"],
["Que signifie « Sugoi » ?","Incroyable","Faible","Compliqué","Calme"],
["Que signifie « Omoshiroi » ?","Drôle / intéressant","Froid","Pratique","Faible"],
["Que signifie « Kirei » ?","Beau / propre","Faible","Chaud","Compliqué"],
["Quel adjectif signifie « délicieux » ?","Oishii","Samui","Benri","Shizuka"],
["Que signifie « Nihongo wa kantan desu » ?","Le japonais, c'est facile","Le japonais est compliqué","Je parle japonais","Le japonais est drôle"],
["Que signifie « Manga wa omoshiroi desu ka » ?","Est-ce que le manga est drôle ?","Le manga est drôle","Le manga est facile","Je lis un manga"],
["Comment demander « Est-ce que le japonais est compliqué ? »","Nihongo wa muzukashii desu ka","Nihongo wa muzukashii desu","Nihongo wa kantan desu","Nihongo ka muzukashii"],
["Que signifie « Niku wa umakunai » ?","La viande n'est pas bonne","La viande est bonne","La viande est chère","J'aime la viande"],
["Que signifie « Sakura wa kanashikunai » ?","Sakura n'est pas triste","Sakura est triste","Sakura est contente","Sakura dort"],
["Que signifie « Onigiri wa takakunai » ?","Les onigiris ne sont pas chers","Les onigiris sont chers","Les onigiris sont bons","Je mange des onigiris"],
["Que signifie « Tokyo wa kitanakunai » ?","Tokyo n'est pas sale","Tokyo est sale","Tokyo est grand","Tokyo est calme"],
["Que signifie « Midoriya wa ureshikunai » ?","Midoriya n'est pas content","Midoriya est content","Midoriya est fort","Midoriya est faible"],
["Que signifie « Rock Lee wa jouzu janai » ?","Rock Lee n'est pas doué","Rock Lee est doué","Rock Lee est triste","Rock Lee dort"],
["Que signifie « Major wa yuumei janai » ?","Major n'est pas connu","Major est connu","Major est pratique","Major est calme"],
["Que signifie « Watashi wa genki jaa arimasen » ?","Je ne vais pas bien","Je vais bien","Je suis français","Je suis fort"],
["Que signifie « Keitai wa benri jaa arimasen » ?","Le téléphone portable n'est pas pratique","Le téléphone portable est pratique","Le téléphone portable est cher","Le téléphone portable est calme"],
["Comment dit-on « Ce n'est pas bon » avec « umai » ?","Umakunai","Umanai","Umai nai","Umaku desu"],
["Comment nier « muzukashii » (compliqué) ?","Muzukashikunai","Muzukashii nai","Muzukashi janai","Muzukashiikunai"],
["Comment nier « kantan » (facile) ?","Kantan janai","Kantankunai","Kantan nai","Kantan ka"]
]
};
